"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jogo_1 = require("./jogo");
var personagens_1 = require("./personagens");
var personagem = new personagens_1.Personagem(1, "person", 20);
var soldado1 = new personagens_1.Soldado(2, "soldier1", 100);
var soldado2 = new personagens_1.Soldado(3, "soldier2", 100);
var cavaleiro = new personagens_1.Cavaleiro(4, "knight", 100);
soldado1.setForcaAtaque(5);
soldado2.setForcaAtaque(7);
cavaleiro.setForcaAtaque(10);
var jogo = new jogo_1.Jogo();
jogo.incluir(personagem);
jogo.incluir(soldado1);
jogo.incluir(soldado2);
jogo.incluir(cavaleiro);
jogo.avaliarBatalha();
jogo.atacar(personagem.id, soldado1.id);
jogo.avaliarBatalha();
jogo.atacar(soldado2.id, soldado1.id);
jogo.avaliarBatalha();
jogo.atacar(cavaleiro.id, soldado2.id);
jogo.avaliarBatalha();
jogo.atacar(cavaleiro.id, soldado2.id);
jogo.avaliarBatalha();
jogo.atacar(soldado1.id, soldado1.id);
jogo.avaliarBatalha();
jogo.atacar(soldado1.id, cavaleiro.id);
jogo.avaliarBatalha();
//# sourceMappingURL=script.js.map